name: test_01
on:
  workflow_dispatch:
env:
  WINE_VERSION: 9.7
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup
        working-directory: /home/runner/work/
        run: |
          sudo apt purge -y ubuntu-advantage-tools
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'

      - name: clone wine-tkg-git repo
        working-directory: /home/runner/work/
        run: git clone https://github.com/Frogging-Family/wine-tkg-git.git

      - name: get/set the caffe recipe
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: |
          curl https://raw.githubusercontent.com/bottlesdevs/build-tools/main/runners/vaniglia/wine-tkg.cfg >> customization.cfg
          sed -i "s/_staging_version=\"\"/_staging_version=\"v$WINE_VERSION\"/g" customization.cfg
          sed -i "s/_plain_version=\"\"/_plain_version=\"wine-$WINE_VERSION\"/g" customization.cfg

      - name: start build
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: yes|./non-makepkg-build.sh

      - name: package
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/non-makepkg-builds/
        run: |
          mv wine-tkg-staging-* caffe-$WINE_VERSION-x86_64
          tar cJvf caffe-$WINE_VERSION-x86_64.tar.xz caffe-$WINE_VERSION-x86_64
          mv caffe-$WINE_VERSION-x86_64.tar.xz /tmp/caffe-$WINE_VERSION-x86_64.tar.xz

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "caffe-${{ env.WINE_VERSION }}"
          title: "Caffe ${{ env.WINE_VERSION }}"
          files: "/tmp/caffe-${{ env.WINE_VERSION }}-x86_64.tar.xz"
