name: valve_wine
on:
  workflow_dispatch:
env:
  WINE_VERSION: '9.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup
        working-directory: /home/runner/work/
        run: |
          sudo apt purge -y ubuntu-advantage-tools
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'

      - name: clone wine-tkg-git repo
        working-directory: /home/runner/work/
        run: |
          git clone https://github.com/Frogging-Family/wine-tkg-git.git
          cd wine-tkg-git/wine-tkg-git
          sed -i 's/distro=""/distro="debuntu"/' customization.cfg
          sed -i 's/LOCAL_PRESET=""/LOCAL_PRESET="valve-exp-bleeding"/' customization.cfg
          sed -i 's/_wayland_driver="false"/_wayland_driver="true"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg

      - name: start build
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: yes|./non-makepkg-build.sh

      - name: package
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/non-makepkg-builds/
        run: |
          mv wine-tkg-staging-* $name-$WINE_VERSION-x86_64
          tar cJvf $name-$WINE_VERSION-x86_64.tar.xz $name-$WINE_VERSION-x86_64
          mv $name-$WINE_VERSION-x86_64.tar.xz /tmp/$name-$WINE_VERSION-x86_64.tar.xz

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "$name-${{ env.WINE_VERSION }}"
          title: "$name ${{ env.WINE_VERSION }}"
          files: "/tmp/$name-${{ env.WINE_VERSION }}-x86_64.tar.xz"
